#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck disable=SC1090
. "$DIR"/../git-shmart

append_and_commit() {
  echo 'foo' >> README
  git add .
  git commit -qm 'add foo'
}

it_does_nothing_when_up_to_date() {
  EXPECTED="Executing: git fetch origin
Neither your local branch 'master', nor the remote branch 'origin/master' have moved on.
Already up-to-date."
  assertEquals "$EXPECTED" "$(shmart_pull)"
}

it_warns_when_not_in_a_git_repo() {
  rm -rf .git
  EXPECTED="You need to run this from within a Git directory.
Current working directory: $(pwd)"
  assertEquals "$EXPECTED" "$(shmart_pull)"
}

it_reports_no_remote_changes_and_one_local_change() {
  append_and_commit
  EXPECTED="Executing: git fetch origin
You have 1 new commit on 'master'.
Remote branch 'origin/master' has not moved on.
Already up-to-date."
  assertEquals "$EXPECTED" "$(shmart_pull)"
}

it_reports_no_remote_changes_and_many_local_changes() {
  append_and_commit
  append_and_commit
  EXPECTED="Executing: git fetch origin
You have 2 new commits on 'master'.
Remote branch 'origin/master' has not moved on.
Already up-to-date."
  assertEquals "$EXPECTED" "$(shmart_pull)"
}

# shellcheck disable=SC1090
. "$DIR"/test_helper
