#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck disable=SC1090
. "$DIR"/../git-shmart

it_does_nothing_when_up_to_date() {
  mkdir local remote
  cd remote
  git init > /dev/null
  git config --local user.name 'Maxwell Smart'
  git config --local user.email 'agent86@control.gov'
  git config --local core.pager 'cat'
  echo 'hurr durr' > README
  mkdir lib
  echo 'puts "pro hax"' > lib/codes.rb
  git add .
  git commit -qm 'first'
  cd ..
  git clone -q remote/.git local
  cd local
  git config --local user.name 'Agent 99'
  git config --local user.email 'agent99@control.gov'
  git config --local core.pager 'cat'
  EXPECTED="Executing: git fetch origin
Neither your local branch 'master', nor the remote branch 'origin/master' have moved on.
Already up-to-date."
  assertEquals "$EXPECTED" "$(shmart_pull)"
}

# shellcheck disable=SC1090
. "$DIR"/test_helper
