#!/bin/bash

SANDBOX="/tmp/git_shmart_sandbox"

build_remote_repo() {
  mkdir -p $SANDBOX/remote
  cd "$_" || exit
  git init > /dev/null
  git config --local user.name 'Remote User'
  git config --local user.email 'remote@example.com'
  git config --local core.pager 'cat'
  echo 'foo' > README
  git add .
  git commit -qm 'first'
}

build_local_repo() {
  mkdir -p $SANDBOX/local
  git clone -q $SANDBOX/remote/.git "$_"
  cd "$_" || exit
  git config --local user.name 'Local User'
  git config --local user.email 'local@example.com'
  git config --local core.pager 'cat'
}

setUp() {
  cd || exit
  rm -rf $SANDBOX
  build_remote_repo
  build_local_repo
  cd $SANDBOX/local || exit
}

oneTimeTearDown() {
  rm -rf $SANDBOX
}

# shellcheck disable=SC2013
suite() {
  for test_name in $(grep '^it_' "$0" | cut -d '(' -f 1); do
    suite_addTest "$test_name"
  done
}

# shellcheck disable=SC1091
. shunit2
