#!/bin/bash

local_branch() {
  git name-rev --name-only HEAD
}

tracking_remote() {
  git config branch."$(local_branch)".remote
}

tracking_branch() {
  git config branch."$(local_branch)".merge | cut -d / -f 3
}

warn_when_not_in_git_repo() {
  if [ "$(git status > /dev/null 2>&1; echo $?)" != "0" ]
  then
    echo "You need to run this from within a Git directory."
    echo "Current working directory: $(pwd)"
    exit 1
  fi
}

fetch() {
  echo "Executing: git fetch origin"
  git fetch origin
}

shmart_pull() {
  warn_when_not_in_git_repo
  fetch

  CURRENT_BRANCH=$(local_branch)
  UPSTREAM_BRANCH=$(tracking_remote)/$(tracking_branch)
  HEAD=$(git rev-parse HEAD)
  REMOTE=$(git rev-parse "$UPSTREAM_BRANCH")

  if [ "$HEAD" == "$REMOTE" ]
  then
    echo "Neither your local branch '$CURRENT_BRANCH', nor the remote branch '$UPSTREAM_BRANCH' have moved on."
  fi

  git pull
}

shmart_log() {
  git log --pretty="format:%C(yellow)%h%Cblue%d%Creset %s %C(white) %an, %ar%Creset" \
          --graph \
          "$@"
}
